anguage: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t chetanrp19/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chetanrp19/react-test npm run test

after_success:
  - docker build -t chetanrp19/multi-client ./client
  - docker build -t chetanrp19/multi-nginx ./nginx
  - docker build -t chetanrp19/multi-server ./server
  - docker build -t chetanrp19/multi-worker ./worker
  # login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images
  - docker push chetanrp19/multi-client
  - docker push chetanrp19/multi-nginx
  - docker push chetanrp19/multi-server
  - docker push chetanrp19/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-903670939170'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

