anguage: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t chetanrp19/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chetanrp19/react-test npm run test

after_success:
  - docker build -t chetanrp19/multi-client ./client
  - docker build -t chetanrp19/multi-nginx ./nginx
  - docker build -t chetanrp19/multi-server ./server
  - docker build -t chetanrp19/multi-worker ./worker